#! /bin/sh
# Run this script to setup the automake environment.
# ./configure
# make
# make install

libtoolize --force --copy
aclocal
autoconf
automake --add-missing
automake

touch src/cmdline.c
touch src/cmdline.h
touch src/cmdline.ggo
