#!/bin/sh

file=$(basename $1)
dir=$(dirname $1)
haserl=/usr/bin/haserl
cd $dir

if [ ${CONTENT_LENGTH:-0} -gt 0 ]; then
    POST_FILE=/tmp/post.$$
    export POST_FILE
    dd of=$POST_FILE count=$CONTENT_LENGTH bs=1 2>/dev/null
    $haserl $file < $POST_FILE
    /bin/rm -f $POST_FILE
else
    $haserl $file
fi
