#!/bin/sh

. /etc/pp/functions

if [ -x /bin/ipkg ] && [ ! -x /usr/sbin/chilli ]; then
  echo "Updating ipkg database"
  ipkg update
  echo "Installing ChilliSpot" 
  ipkg install chillispot
fi

[ -z $TYPE ] && TYPE="chillispot"
[ -z $HOST ] && HOST="staging.picopoint.com"
[ -z $SHSECRET ] && SHSECRET="<required>"
[ -z $UAMPROTO ] && UAMPROTO="https"
[ -z $ADMUSR ] && ADMUSR="chillispot"
[ -z $ADMPWD ] && ADMPWD="chillispot"

echo -n "Enter UAM/RADIUS Server [$HOST]: "; read n
[ -n "$n" ] && HOST="$n"

echo -n "Enter RADIUS shared secret [$SHSECRET]: "; read n
[ -n "$n" ] && SHSECRET="$n"

echo -n "Enter RADIUS Administrative user [$ADMUSR]: "; read n
[ -n "$n" ] && ADMUSR="$n"

echo -n "Enter RADIUS Administrative user password [$ADMPWD]: "; read n
[ -n "$n" ] && ADMPWD="$n"

while [ -z "$NASID" ]; do
    echo -n "Enter unique NAS-Identifier: "; read NASID
    [ -z "$NASID" ] && echo "NAS-Identifier is required"
done

while [ -z "$UAMSECRET" ]; do
    echo -n "Enter UAM Secret: "; read UAMSECRET
    [ -z "$UAMSECRET" ] && echo "UAM Secret is required"
done

while [ -z "$WANIF" ]; do
    echo -n "Enter your WAN/Internet interface (e.g. eth0): "; read WANIF
    [ -z "$WANIF" ] && echo "WAN interface is required"
    NASIP=$(ifconfig $WANIF 2>/dev/null|grep 'inet addr'|awk -F: '{print $2}'|awk '{print $1}')
    if [ -z $NASIP ]; then
	echo "Invalid interface: Internet connection required!"
	WANIF=
    fi
done

while [ -z "$LANIF" ]; do
    echo -n "Enter your LAN/ChilliSpot interface (e.g. eth1): "; read LANIF
    [ -z "$LANIF" ] && echo "LAN interface is required"
    NASMAC=$(ifconfig $LANIF 2>/dev/null|grep HWaddr|awk '{print $5}')
    if [ -z $NASMAC ]; then
	echo "Invalid interface"
	LANIF=
    fi
done

echo -n "Enter the SSID of the location [$SSID]: "; read n
[ -n "$n" ] && SSID="$n"

cat > /etc/pp/config <<EOF
type            $TYPE
host            $HOST
proto           $UAMPROTO
uamsecret       $UAMSECRET
sharedsecret    $SHSECRET
nasid           $NASID
admusr          $ADMUSR
admpwd          $ADMPWD
lan_interface   $LANIF
wan_interface   $WANIF
ssid            $SSID
nasmac          $NASMAC
nasip           $NASIP
EOF

echo "Saved configuration in /etc/pp/config"

/sbin/chkconfig --del chilli
/sbin/chkconfig --add chilli
